# Generated by Django 5.0.6 on 2026-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web')], default='web', max_length=16),
        ),
    ]
